name: clipseg-environment
channels:
  - conda-forge
  - pytorch
dependencies:
  - numpy
  - scipy
  - pytorch
  - torchvision
  - cpuonly  # only for binder
  - matplotlib
  - pip
  - pip:
    - opencv-python
    - git+https://github.com/openai/CLIP.git
